//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.24 at 04:56:02 PM CST 
//


package com.proyectosw.hotel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.proyectosw.hotel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.proyectosw.hotel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CancelarReservacionResponse }
     * 
     */
    public CancelarReservacionResponse createCancelarReservacionResponse() {
        return new CancelarReservacionResponse();
    }

    /**
     * Create an instance of {@link HacerReservacionResponse }
     * 
     */
    public HacerReservacionResponse createHacerReservacionResponse() {
        return new HacerReservacionResponse();
    }

    /**
     * Create an instance of {@link EditarHabitacionRequest }
     * 
     */
    public EditarHabitacionRequest createEditarHabitacionRequest() {
        return new EditarHabitacionRequest();
    }

    /**
     * Create an instance of {@link EliminarHabitacionRequest }
     * 
     */
    public EliminarHabitacionRequest createEliminarHabitacionRequest() {
        return new EliminarHabitacionRequest();
    }

    /**
     * Create an instance of {@link RegistrarClienteRequest }
     * 
     */
    public RegistrarClienteRequest createRegistrarClienteRequest() {
        return new RegistrarClienteRequest();
    }

    /**
     * Create an instance of {@link RegistrarCheckInRequest }
     * 
     */
    public RegistrarCheckInRequest createRegistrarCheckInRequest() {
        return new RegistrarCheckInRequest();
    }

    /**
     * Create an instance of {@link EditarHabitacionResponse }
     * 
     */
    public EditarHabitacionResponse createEditarHabitacionResponse() {
        return new EditarHabitacionResponse();
    }

    /**
     * Create an instance of {@link BuscarReservacionResponse }
     * 
     */
    public BuscarReservacionResponse createBuscarReservacionResponse() {
        return new BuscarReservacionResponse();
    }

    /**
     * Create an instance of {@link RegistrarCheckInResponse }
     * 
     */
    public RegistrarCheckInResponse createRegistrarCheckInResponse() {
        return new RegistrarCheckInResponse();
    }

    /**
     * Create an instance of {@link HacerReservacionRequest }
     * 
     */
    public HacerReservacionRequest createHacerReservacionRequest() {
        return new HacerReservacionRequest();
    }

    /**
     * Create an instance of {@link RegistrarCheckOutResponse }
     * 
     */
    public RegistrarCheckOutResponse createRegistrarCheckOutResponse() {
        return new RegistrarCheckOutResponse();
    }

    /**
     * Create an instance of {@link EliminarClienteResponse }
     * 
     */
    public EliminarClienteResponse createEliminarClienteResponse() {
        return new EliminarClienteResponse();
    }

    /**
     * Create an instance of {@link AgregarHabitacionResponse }
     * 
     */
    public AgregarHabitacionResponse createAgregarHabitacionResponse() {
        return new AgregarHabitacionResponse();
    }

    /**
     * Create an instance of {@link EliminarHabitacionResponse }
     * 
     */
    public EliminarHabitacionResponse createEliminarHabitacionResponse() {
        return new EliminarHabitacionResponse();
    }

    /**
     * Create an instance of {@link CancelarReservacionRequest }
     * 
     */
    public CancelarReservacionRequest createCancelarReservacionRequest() {
        return new CancelarReservacionRequest();
    }

    /**
     * Create an instance of {@link AgregarHabitacionRequest }
     * 
     */
    public AgregarHabitacionRequest createAgregarHabitacionRequest() {
        return new AgregarHabitacionRequest();
    }

    /**
     * Create an instance of {@link AplazarEstanciaResponse }
     * 
     */
    public AplazarEstanciaResponse createAplazarEstanciaResponse() {
        return new AplazarEstanciaResponse();
    }

    /**
     * Create an instance of {@link EditarClienteResponse }
     * 
     */
    public EditarClienteResponse createEditarClienteResponse() {
        return new EditarClienteResponse();
    }

    /**
     * Create an instance of {@link RegistrarCheckOutRequest }
     * 
     */
    public RegistrarCheckOutRequest createRegistrarCheckOutRequest() {
        return new RegistrarCheckOutRequest();
    }

    /**
     * Create an instance of {@link EliminarClienteRequest }
     * 
     */
    public EliminarClienteRequest createEliminarClienteRequest() {
        return new EliminarClienteRequest();
    }

    /**
     * Create an instance of {@link RegistrarClienteResponse }
     * 
     */
    public RegistrarClienteResponse createRegistrarClienteResponse() {
        return new RegistrarClienteResponse();
    }

    /**
     * Create an instance of {@link EditarReservacionRequest }
     * 
     */
    public EditarReservacionRequest createEditarReservacionRequest() {
        return new EditarReservacionRequest();
    }

    /**
     * Create an instance of {@link BuscarReservacionRequest }
     * 
     */
    public BuscarReservacionRequest createBuscarReservacionRequest() {
        return new BuscarReservacionRequest();
    }

    /**
     * Create an instance of {@link AplazarEstanciaRequest }
     * 
     */
    public AplazarEstanciaRequest createAplazarEstanciaRequest() {
        return new AplazarEstanciaRequest();
    }

    /**
     * Create an instance of {@link EditarReservacionResponse }
     * 
     */
    public EditarReservacionResponse createEditarReservacionResponse() {
        return new EditarReservacionResponse();
    }

    /**
     * Create an instance of {@link EditarClienteRequest }
     * 
     */
    public EditarClienteRequest createEditarClienteRequest() {
        return new EditarClienteRequest();
    }

}
