//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 02:46:27 PM CDT 
//


package com.proyectosw.hotel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.proyectosw.hotel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.proyectosw.hotel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerHabitacionesPorStatusResponse }
     * 
     */
    public ObtenerHabitacionesPorStatusResponse createObtenerHabitacionesPorStatusResponse() {
        return new ObtenerHabitacionesPorStatusResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaClientesResponse }
     * 
     */
    public ObtenerListaClientesResponse createObtenerListaClientesResponse() {
        return new ObtenerListaClientesResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaReservacionesResponse }
     * 
     */
    public ObtenerListaReservacionesResponse createObtenerListaReservacionesResponse() {
        return new ObtenerListaReservacionesResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaEstanciasResponse }
     * 
     */
    public ObtenerListaEstanciasResponse createObtenerListaEstanciasResponse() {
        return new ObtenerListaEstanciasResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaHabitacionesResponse }
     * 
     */
    public ObtenerListaHabitacionesResponse createObtenerListaHabitacionesResponse() {
        return new ObtenerListaHabitacionesResponse();
    }

    /**
     * Create an instance of {@link CancelarReservacionResponse }
     * 
     */
    public CancelarReservacionResponse createCancelarReservacionResponse() {
        return new CancelarReservacionResponse();
    }

    /**
     * Create an instance of {@link ObtenerHabitacionesPorStatusResponse.Habitacion }
     * 
     */
    public ObtenerHabitacionesPorStatusResponse.Habitacion createObtenerHabitacionesPorStatusResponseHabitacion() {
        return new ObtenerHabitacionesPorStatusResponse.Habitacion();
    }

    /**
     * Create an instance of {@link ObtenerListaReservacionesRequest }
     * 
     */
    public ObtenerListaReservacionesRequest createObtenerListaReservacionesRequest() {
        return new ObtenerListaReservacionesRequest();
    }

    /**
     * Create an instance of {@link HacerReservacionResponse }
     * 
     */
    public HacerReservacionResponse createHacerReservacionResponse() {
        return new HacerReservacionResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaHabitacionesRequest }
     * 
     */
    public ObtenerListaHabitacionesRequest createObtenerListaHabitacionesRequest() {
        return new ObtenerListaHabitacionesRequest();
    }

    /**
     * Create an instance of {@link ModificarEstanciaResponse }
     * 
     */
    public ModificarEstanciaResponse createModificarEstanciaResponse() {
        return new ModificarEstanciaResponse();
    }

    /**
     * Create an instance of {@link ModificarEstanciaRequest }
     * 
     */
    public ModificarEstanciaRequest createModificarEstanciaRequest() {
        return new ModificarEstanciaRequest();
    }

    /**
     * Create an instance of {@link EditarHabitacionRequest }
     * 
     */
    public EditarHabitacionRequest createEditarHabitacionRequest() {
        return new EditarHabitacionRequest();
    }

    /**
     * Create an instance of {@link ConsultarEstanciaResponse }
     * 
     */
    public ConsultarEstanciaResponse createConsultarEstanciaResponse() {
        return new ConsultarEstanciaResponse();
    }

    /**
     * Create an instance of {@link ConsultarClienteRequest }
     * 
     */
    public ConsultarClienteRequest createConsultarClienteRequest() {
        return new ConsultarClienteRequest();
    }

    /**
     * Create an instance of {@link ObtenerListaClientesResponse.Cliente }
     * 
     */
    public ObtenerListaClientesResponse.Cliente createObtenerListaClientesResponseCliente() {
        return new ObtenerListaClientesResponse.Cliente();
    }

    /**
     * Create an instance of {@link EliminarHabitacionRequest }
     * 
     */
    public EliminarHabitacionRequest createEliminarHabitacionRequest() {
        return new EliminarHabitacionRequest();
    }

    /**
     * Create an instance of {@link RegistrarClienteRequest }
     * 
     */
    public RegistrarClienteRequest createRegistrarClienteRequest() {
        return new RegistrarClienteRequest();
    }

    /**
     * Create an instance of {@link ObtenerListaClientesRequest }
     * 
     */
    public ObtenerListaClientesRequest createObtenerListaClientesRequest() {
        return new ObtenerListaClientesRequest();
    }

    /**
     * Create an instance of {@link RealizarCheckOutRequest }
     * 
     */
    public RealizarCheckOutRequest createRealizarCheckOutRequest() {
        return new RealizarCheckOutRequest();
    }

    /**
     * Create an instance of {@link ConsultarClienteResponse }
     * 
     */
    public ConsultarClienteResponse createConsultarClienteResponse() {
        return new ConsultarClienteResponse();
    }

    /**
     * Create an instance of {@link EditarHabitacionResponse }
     * 
     */
    public EditarHabitacionResponse createEditarHabitacionResponse() {
        return new EditarHabitacionResponse();
    }

    /**
     * Create an instance of {@link HacerReservacionRequest }
     * 
     */
    public HacerReservacionRequest createHacerReservacionRequest() {
        return new HacerReservacionRequest();
    }

    /**
     * Create an instance of {@link EliminarClienteResponse }
     * 
     */
    public EliminarClienteResponse createEliminarClienteResponse() {
        return new EliminarClienteResponse();
    }

    /**
     * Create an instance of {@link AgregarHabitacionResponse }
     * 
     */
    public AgregarHabitacionResponse createAgregarHabitacionResponse() {
        return new AgregarHabitacionResponse();
    }

    /**
     * Create an instance of {@link ConsultarHabitacionResponse }
     * 
     */
    public ConsultarHabitacionResponse createConsultarHabitacionResponse() {
        return new ConsultarHabitacionResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaEstanciasRequest }
     * 
     */
    public ObtenerListaEstanciasRequest createObtenerListaEstanciasRequest() {
        return new ObtenerListaEstanciasRequest();
    }

    /**
     * Create an instance of {@link EliminarHabitacionResponse }
     * 
     */
    public EliminarHabitacionResponse createEliminarHabitacionResponse() {
        return new EliminarHabitacionResponse();
    }

    /**
     * Create an instance of {@link ObtenerHabitacionesPorStatusRequest }
     * 
     */
    public ObtenerHabitacionesPorStatusRequest createObtenerHabitacionesPorStatusRequest() {
        return new ObtenerHabitacionesPorStatusRequest();
    }

    /**
     * Create an instance of {@link ObtenerListaReservacionesResponse.Reservacion }
     * 
     */
    public ObtenerListaReservacionesResponse.Reservacion createObtenerListaReservacionesResponseReservacion() {
        return new ObtenerListaReservacionesResponse.Reservacion();
    }

    /**
     * Create an instance of {@link CancelarReservacionRequest }
     * 
     */
    public CancelarReservacionRequest createCancelarReservacionRequest() {
        return new CancelarReservacionRequest();
    }

    /**
     * Create an instance of {@link AgregarHabitacionRequest }
     * 
     */
    public AgregarHabitacionRequest createAgregarHabitacionRequest() {
        return new AgregarHabitacionRequest();
    }

    /**
     * Create an instance of {@link RealizarCheckInResponse }
     * 
     */
    public RealizarCheckInResponse createRealizarCheckInResponse() {
        return new RealizarCheckInResponse();
    }

    /**
     * Create an instance of {@link ObtenerListaEstanciasResponse.Estancia }
     * 
     */
    public ObtenerListaEstanciasResponse.Estancia createObtenerListaEstanciasResponseEstancia() {
        return new ObtenerListaEstanciasResponse.Estancia();
    }

    /**
     * Create an instance of {@link ConsultarEstanciaRequest }
     * 
     */
    public ConsultarEstanciaRequest createConsultarEstanciaRequest() {
        return new ConsultarEstanciaRequest();
    }

    /**
     * Create an instance of {@link EditarClienteResponse }
     * 
     */
    public EditarClienteResponse createEditarClienteResponse() {
        return new EditarClienteResponse();
    }

    /**
     * Create an instance of {@link RealizarCheckInRequest }
     * 
     */
    public RealizarCheckInRequest createRealizarCheckInRequest() {
        return new RealizarCheckInRequest();
    }

    /**
     * Create an instance of {@link RealizarCheckOutResponse }
     * 
     */
    public RealizarCheckOutResponse createRealizarCheckOutResponse() {
        return new RealizarCheckOutResponse();
    }

    /**
     * Create an instance of {@link EliminarClienteRequest }
     * 
     */
    public EliminarClienteRequest createEliminarClienteRequest() {
        return new EliminarClienteRequest();
    }

    /**
     * Create an instance of {@link ConsultarReservacionResponse }
     * 
     */
    public ConsultarReservacionResponse createConsultarReservacionResponse() {
        return new ConsultarReservacionResponse();
    }

    /**
     * Create an instance of {@link ConsultarReservacionPorClienteResponse }
     * 
     */
    public ConsultarReservacionPorClienteResponse createConsultarReservacionPorClienteResponse() {
        return new ConsultarReservacionPorClienteResponse();
    }

    /**
     * Create an instance of {@link RegistrarClienteResponse }
     * 
     */
    public RegistrarClienteResponse createRegistrarClienteResponse() {
        return new RegistrarClienteResponse();
    }

    /**
     * Create an instance of {@link EditarReservacionRequest }
     * 
     */
    public EditarReservacionRequest createEditarReservacionRequest() {
        return new EditarReservacionRequest();
    }

    /**
     * Create an instance of {@link ConsultarReservacionPorClienteRequest }
     * 
     */
    public ConsultarReservacionPorClienteRequest createConsultarReservacionPorClienteRequest() {
        return new ConsultarReservacionPorClienteRequest();
    }

    /**
     * Create an instance of {@link EditarReservacionResponse }
     * 
     */
    public EditarReservacionResponse createEditarReservacionResponse() {
        return new EditarReservacionResponse();
    }

    /**
     * Create an instance of {@link ConsultarHabitacionRequest }
     * 
     */
    public ConsultarHabitacionRequest createConsultarHabitacionRequest() {
        return new ConsultarHabitacionRequest();
    }

    /**
     * Create an instance of {@link ObtenerListaHabitacionesResponse.Habitacion }
     * 
     */
    public ObtenerListaHabitacionesResponse.Habitacion createObtenerListaHabitacionesResponseHabitacion() {
        return new ObtenerListaHabitacionesResponse.Habitacion();
    }

    /**
     * Create an instance of {@link ConsultarReservacionRequest }
     * 
     */
    public ConsultarReservacionRequest createConsultarReservacionRequest() {
        return new ConsultarReservacionRequest();
    }

    /**
     * Create an instance of {@link EditarClienteRequest }
     * 
     */
    public EditarClienteRequest createEditarClienteRequest() {
        return new EditarClienteRequest();
    }

}
