//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 02:46:27 PM CDT 
//


package com.proyectosw.hotel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estancia" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numHabitacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numAdultos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numNinos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tipoHabitacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaCheckIn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaCheckOut" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="precio" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                   &lt;element name="idCliente" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="idEstancia" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "estancia"
})
@XmlRootElement(name = "ObtenerListaEstanciasResponse")
public class ObtenerListaEstanciasResponse {

    @XmlElement(required = true)
    protected List<ObtenerListaEstanciasResponse.Estancia> estancia;

    /**
     * Gets the value of the estancia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the estancia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstancia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObtenerListaEstanciasResponse.Estancia }
     * 
     * 
     */
    public List<ObtenerListaEstanciasResponse.Estancia> getEstancia() {
        if (estancia == null) {
            estancia = new ArrayList<ObtenerListaEstanciasResponse.Estancia>();
        }
        return this.estancia;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numHabitacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numAdultos" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numNinos" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="tipoHabitacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fechaCheckIn" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fechaCheckOut" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="precio" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *         &lt;element name="idCliente" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="idEstancia" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numHabitacion",
        "numAdultos",
        "numNinos",
        "tipoHabitacion",
        "fechaCheckIn",
        "fechaCheckOut",
        "status",
        "precio",
        "idCliente",
        "idEstancia"
    })
    public static class Estancia {

        protected int numHabitacion;
        protected int numAdultos;
        protected int numNinos;
        @XmlElement(required = true)
        protected String tipoHabitacion;
        @XmlElement(required = true)
        protected String fechaCheckIn;
        @XmlElement(required = true)
        protected String fechaCheckOut;
        @XmlElement(required = true)
        protected String status;
        protected double precio;
        protected int idCliente;
        protected int idEstancia;

        public Estancia() {}
        
        public Estancia(int numHabitacion, int numAdultos, int numNinos, String tipoHabitacion, String fechaCheckIn,
				String fechaCheckOut, String status, double precio, int idCliente, int idEstancia) {
			super();
			this.numHabitacion = numHabitacion;
			this.numAdultos = numAdultos;
			this.numNinos = numNinos;
			this.tipoHabitacion = tipoHabitacion;
			this.fechaCheckIn = fechaCheckIn;
			this.fechaCheckOut = fechaCheckOut;
			this.status = status;
			this.precio = precio;
			this.idCliente = idCliente;
			this.idEstancia = idEstancia;
		}

		/**
         * Gets the value of the numHabitacion property.
         * 
         */
        public int getNumHabitacion() {
            return numHabitacion;
        }

        /**
         * Sets the value of the numHabitacion property.
         * 
         */
        public void setNumHabitacion(int value) {
            this.numHabitacion = value;
        }

        /**
         * Gets the value of the numAdultos property.
         * 
         */
        public int getNumAdultos() {
            return numAdultos;
        }

        /**
         * Sets the value of the numAdultos property.
         * 
         */
        public void setNumAdultos(int value) {
            this.numAdultos = value;
        }

        /**
         * Gets the value of the numNinos property.
         * 
         */
        public int getNumNinos() {
            return numNinos;
        }

        /**
         * Sets the value of the numNinos property.
         * 
         */
        public void setNumNinos(int value) {
            this.numNinos = value;
        }

        /**
         * Gets the value of the tipoHabitacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoHabitacion() {
            return tipoHabitacion;
        }

        /**
         * Sets the value of the tipoHabitacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoHabitacion(String value) {
            this.tipoHabitacion = value;
        }

        /**
         * Gets the value of the fechaCheckIn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaCheckIn() {
            return fechaCheckIn;
        }

        /**
         * Sets the value of the fechaCheckIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaCheckIn(String value) {
            this.fechaCheckIn = value;
        }

        /**
         * Gets the value of the fechaCheckOut property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaCheckOut() {
            return fechaCheckOut;
        }

        /**
         * Sets the value of the fechaCheckOut property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaCheckOut(String value) {
            this.fechaCheckOut = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the precio property.
         * 
         */
        public double getPrecio() {
            return precio;
        }

        /**
         * Sets the value of the precio property.
         * 
         */
        public void setPrecio(double value) {
            this.precio = value;
        }

        /**
         * Gets the value of the idCliente property.
         * 
         */
        public int getIdCliente() {
            return idCliente;
        }

        /**
         * Sets the value of the idCliente property.
         * 
         */
        public void setIdCliente(int value) {
            this.idCliente = value;
        }

        /**
         * Gets the value of the idEstancia property.
         * 
         */
        public int getIdEstancia() {
            return idEstancia;
        }

        /**
         * Sets the value of the idEstancia property.
         * 
         */
        public void setIdEstancia(int value) {
            this.idEstancia = value;
        }

    }

}
