//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.15 at 02:46:27 PM CDT 
//


package com.proyectosw.hotel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="habitacion" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="numHabitacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="piso" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="numCamas" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="cupoPersonas" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tipoHabitacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "habitacion"
})
@XmlRootElement(name = "ObtenerListaHabitacionesResponse")
public class ObtenerListaHabitacionesResponse {

    @XmlElement(required = true)
    protected List<ObtenerListaHabitacionesResponse.Habitacion> habitacion;

    /**
     * Gets the value of the habitacion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the habitacion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHabitacion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObtenerListaHabitacionesResponse.Habitacion }
     * 
     * 
     */
    public List<ObtenerListaHabitacionesResponse.Habitacion> getHabitacion() {
        if (habitacion == null) {
            habitacion = new ArrayList<ObtenerListaHabitacionesResponse.Habitacion>();
        }
        return this.habitacion;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="numHabitacion" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="piso" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="numCamas" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="cupoPersonas" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="tipoHabitacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "numHabitacion",
        "piso",
        "numCamas",
        "cupoPersonas",
        "tipoHabitacion",
        "status"
    })
    public static class Habitacion {

        protected int numHabitacion;
        protected int piso;
        protected int numCamas;
        protected int cupoPersonas;
        @XmlElement(required = true)
        protected String tipoHabitacion;
        @XmlElement(required = true)
        protected String status;

        public Habitacion() {}
        
        public Habitacion(int numHabitacion, int piso, int numCamas, int cupoPersonas, String tipoHabitacion,
				String status) {
			super();
			this.numHabitacion = numHabitacion;
			this.piso = piso;
			this.numCamas = numCamas;
			this.cupoPersonas = cupoPersonas;
			this.tipoHabitacion = tipoHabitacion;
			this.status = status;
		}

		/**
         * Gets the value of the numHabitacion property.
         * 
         */
        public int getNumHabitacion() {
            return numHabitacion;
        }

        /**
         * Sets the value of the numHabitacion property.
         * 
         */
        public void setNumHabitacion(int value) {
            this.numHabitacion = value;
        }

        /**
         * Gets the value of the piso property.
         * 
         */
        public int getPiso() {
            return piso;
        }

        /**
         * Sets the value of the piso property.
         * 
         */
        public void setPiso(int value) {
            this.piso = value;
        }

        /**
         * Gets the value of the numCamas property.
         * 
         */
        public int getNumCamas() {
            return numCamas;
        }

        /**
         * Sets the value of the numCamas property.
         * 
         */
        public void setNumCamas(int value) {
            this.numCamas = value;
        }

        /**
         * Gets the value of the cupoPersonas property.
         * 
         */
        public int getCupoPersonas() {
            return cupoPersonas;
        }

        /**
         * Sets the value of the cupoPersonas property.
         * 
         */
        public void setCupoPersonas(int value) {
            this.cupoPersonas = value;
        }

        /**
         * Gets the value of the tipoHabitacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoHabitacion() {
            return tipoHabitacion;
        }

        /**
         * Sets the value of the tipoHabitacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoHabitacion(String value) {
            this.tipoHabitacion = value;
        }

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

    }

}
